include:
  - docker-compose.base.yaml

services:

  train-text:
    image: ${DOCKER_USERNAME}/train-text:${DEVICE}
    env_file:
      - .env
    environment:
      DEVICE: ${DEVICE:-cpu}
      GIT_COMMIT: ${GIT_COMMIT:-unknown}
      GIT_BRANCH: ${GIT_BRANCH:-unknown}
    networks:
      - mlops-network

  finetune-text:
    image: ${DOCKER_USERNAME}/train-text:${DEVICE}
    env_file:
      - .env
    environment:
      DEVICE: ${DEVICE:-cpu}
    networks:
      - mlops-network

  evaluate-text:
    image: ${DOCKER_USERNAME}/evaluate-text:${DEVICE}
    env_file:
      - .env
    environment:
      DEVICE: ${DEVICE:-cpu}
    networks:
      - mlops-network

  bentoml:
    image: ${DOCKER_USERNAME}/rakuten-text-service:latest
    ports:
      - "3000:3000"
    environment:
      - BENTO_USER=${BENTO_USER}
      - BENTO_PASS=${BENTO_PASS}
      - BENTO_JWT_SECRET=${BENTO_JWT_SECRET}
    restart: unless-stopped
    networks:
      - mlops-network

  streamlit:
    image: ${DOCKER_USERNAME}/streamlit:latest
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_ADMIN_PASSWORD=${STREAMLIT_ADMIN_PASSWORD}
      - STREAMLIT_DEMO_PASSWORD=${STREAMLIT_DEMO_PASSWORD}
      - STREAMLIT_BASE_URL=${STREAMLIT_BASE_URL}
      - STREAMLIT_BENTO_USER=${STREAMLIT_BENTO_USER}
      - STREAMLIT_BENTO_PASS=${STREAMLIT_BENTO_PASS}
      - STREAMLIT_API_KEY=${STREAMLIT_API_KEY}
    volumes:
      - ./data:/app/data
      - ./streamlit:/app/streamlit
    restart: unless-stopped
    networks:
      - mlops-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - mlops-network
