services:

  train-text:
    image: ${DOCKER_USERNAME}/train-text:latest
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./configs:/app/configs
      - ./artifacts:/app/artifacts

  evaluate-text:
    image: ${DOCKER_USERNAME}/evaluate-text:latest
    volumes:
      - ./results:/app/results

  inference:
    image: ${DOCKER_USERNAME}/inference:latest
    volumes:
      - ./results:/app/results

volumes:
  dvc-cache: