stages:
  preprocess-text:
    cmd: uv run python -m src.pipeline.preprocess_text_pipeline
    deps:
      - data/raw/X_train_update.csv
      - data/raw/Y_train_CVw08PX.csv
      - data/raw/pseudo_labeled_samples.csv
      - configs/text_preprocessing_config.yaml
      - configs/label_encoding.json
      - src/
    outs:
      - data/processed/
      - artifacts/splits/

  train-text:
    cmd: uv run python -m src.pipeline.text_pipeline --mode ${TRAIN_MODE}
    deps:
      - data/processed/
      - configs/text_train_config.yaml
      - configs/text_preprocessing_config.yaml
      - src/
    params:
      - configs/text_train_config.yaml:
          - training
          - model
    metrics:
      - results/dvc_metrics.json:
          cache: false
