stages:
  train-text:
    cmd: uv run python -m src.pipeline.text_pipeline --mode train
    deps:
      - data/raw/X_train_update.csv
      - data/raw/Y_train_CVw08PX.csv
      - configs/text_train_config.yaml
      - configs/text_preprocessing_config.yaml
      - src/
    params:
      - configs/text_train_config.yaml:
          - training
          - model
    outs:
      - artifacts/splits/
      - data/processed/
    metrics:
      - results/dvc_metrics.json:
          cache: false
