version: "3.8"

services:
  rakuten-streamlit:
    build:
      context: ..
      dockerfile: streamlit/Dockerfile
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/streamlit/data
      - ./config.yaml:/app/streamlit/config.yaml
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
