training:
  learning_rate: 0.00002
  early_stopping_patience: 1
  num_epochs: 2
  batch_size: 32
  weight_decay: 0.05
  num_workers: 1
  seed: 42

model:
  name: bert-base-multilingual-cased
  pretrained: true
  freeze_backbone: false

data:
  label_col: prdtypecode
  encoded_label_col: label
  designation_col: designation
  description_col: description
  return_quality_report: false

metrics:
  main_metric: macro_f1
  compute_per_class_f1: true
