preprocessing:
  tokenizer_model: bert-base-multilingual-cased
  max_length: 256
  remove_html: true
  lowercase: false
  combine_fields: true
  separator: " Description: "

quality:
  compute_quality_report: false
